[package]
name = "pretty-snowflake"
version = "1.3.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-snowflake = "0.5"
itertools = "0.10"
lazy_static = "1.4"
serde = { version = "1", features = ["derive"] }
tailcall = "0.1"
thiserror = "1"
validator = { version = "0.14", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1"
claim = "0.5"
regex = "1.5"
rand = "0.8"
