[package]
name = "pretty-snowflake"
version = "1.3.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-snowflake = "0.5.0"
itertools = "0.10.1"
once_cell = "1.8.0"
serde = { version = "1.0.130", features = ["derive"] }
tailcall = "0.1.6"
thiserror = "1.0.30"
validator = { version = "0.14.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.0.0"
claim = "0.5.0"
regex = "1.5.4"
rand = "0.8.4"
